export const MODULES = [
  {
    slug: "teardowns",
    label: "Teardown Builder",
    icon: "Wrench",
    description: "Research and publish product teardowns to your portfolio.",
    href: "/dashboard/teardowns",
    color: "var(--accent-amber)",
  },
  {
    slug: "wordweaver",
    label: "WordWeaver",
    icon: "PenTool",
    description: "Create blog posts and podcast content with your voice profile.",
    href: "/dashboard/wordweaver",
    color: "var(--accent-green)",
  },
  {
    slug: "resume",
    label: "Resume Customizer",
    icon: "FileText",
    description: "Tailor resumes and application packages to job descriptions.",
    href: "/dashboard/resume",
    color: "var(--accent-blue)",
  },
  {
    slug: "job-central",
    label: "Job Central",
    icon: "Target",
    description: "Track applications, prep for interviews, manage your job search.",
    href: "/dashboard/job-central",
    color: "var(--accent-red)",
  },
  {
    slug: "madlab",
    label: "MadLab",
    icon: "Beaker",
    description: "Build and publish prototype overview pages for MadLab.",
    href: "/dashboard/madlab",
    color: "var(--accent-cyan, #67e8f9)",
  },
  {
    slug: "fenix",
    label: "Fenix Dashboard",
    icon: "Bot",
    description: "Analytics, failure detection, and training for the Fenix AI assistant.",
    href: "/dashboard/fenix",
    color: "var(--accent-orange, #fb923c)",
  },
  {
    slug: "fenix-journal",
    label: "Fenix Journal",
    icon: "BookOpen",
    description: "Review Fenix's daily diary entries and observations.",
    href: "/dashboard/fenix-journal",
    color: "var(--accent-teal, #2dd4bf)",
  },
  {
    slug: "content-audit",
    label: "Content Audit",
    icon: "Shield",
    description: "Scan site content against voice and accuracy rules.",
    href: "/dashboard/content-audit",
    color: "var(--accent-purple, #a78bfa)",
  },
  {
    slug: "feedback",
    label: "Feedback & Testimonials",
    icon: "MessageSquare",
    description: "View site feedback and manage testimonial submissions.",
    href: "/dashboard/feedback",
    color: "var(--accent-pink, #f472b6)",
  },
  {
    slug: "tools",
    label: "Tools & Links",
    icon: "ExternalLink",
    description: "Analytics dashboards, infrastructure, and external tools.",
    href: "/dashboard/tools",
    color: "var(--text-muted)",
  },
] as const;

export const APP_NAME = "Command Center";
