#!/usr/bin/env python3
"""
Seed the visual_assets collection from the canonical inventory.

Source of truth (until migration): prototypes/visual-asset-inventory.html
This script creates one record per asset with appropriate status, specs, and
metadata. Run once to populate the CC database; subsequent updates happen via
the API as work progresses.

Usage:
    cd command-center/backend
    python3 scripts/seed_visual_assets.py
"""

import json
from pathlib import Path
from datetime import datetime
import uuid

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "visual_assets" / "items.json"


def asset(
    name: str,
    category: str,
    purpose: str,
    status: str = "uncommitted",
    subcategory: str = None,
    where_deployed: str = None,
    dimensions: str = None,
    aspect_ratio: str = None,
    file_format: str = None,
    file_size_target: str = None,
    quantity: int = 1,
    output_path: str = None,
    naming_pattern: str = None,
    style_direction: str = None,
    source_method: str = None,
    preview_image_url: str = None,
    owner: str = "tbd",
    estimated_effort: str = None,
    notes: str = None,
):
    now = datetime.utcnow().isoformat() + "Z"
    return {
        "id": str(uuid.uuid4()),
        "name": name,
        "category": category,
        "subcategory": subcategory,
        "status": status,
        "purpose": purpose,
        "where_deployed": where_deployed,
        "dimensions": dimensions,
        "aspect_ratio": aspect_ratio,
        "file_format": file_format,
        "file_size_target": file_size_target,
        "quantity": quantity,
        "output_path": output_path,
        "naming_pattern": naming_pattern,
        "style_direction": style_direction,
        "palette_constraints": None,
        "typography_rules": None,
        "composition_rules": None,
        "source_method": source_method,
        "generation_tool": None,
        "style_ref": None,
        "preview_image_url": preview_image_url,
        "inspiration_links": [],
        "owner": owner,
        "estimated_effort": estimated_effort,
        "linked_action_items": [],
        "related_assets": [],
        "notes": notes,
        "created_at": now,
        "updated_at": now,
        "shipped_at": now if status == "shipped" else None,
    }


# ── SEED DATA ────────────────────────────────────────────────────
# Every entry below is one row from the HTML inventory.
# Status reflects current ground truth.

ITEMS = [

    # ─── 02. SITE IDENTITY ──────────────────────────────────────
    asset(
        name="Hero scene",
        category="site-identity", subcategory="hero",
        status="shipped", owner="kiran",
        purpose="Full-bleed homepage hero. Painterly Pixar-style studio with Bernese mountain dog, Golden Gate Bridge, cork board, sketchbook, monitor glow.",
        where_deployed="Top of index.html (lines 147-152)",
        aspect_ratio="~21:9",
        file_format="PNG + WebP",
        output_path="images/final-hero-image3.png",
        style_direction="Pixar painterly, warm golden hour, tilt-shift quality",
        source_method="Midjourney",
        preview_image_url="/images/final-hero-image3.png",
    ),
    asset(
        name="Favicon — favicon.ico",
        category="site-identity", subcategory="favicon",
        status="shipped", owner="kiran",
        purpose="Multi-resolution browser tab icon (16, 32, 48px)",
        dimensions="16/32/48px multi-res",
        file_format="ICO",
        output_path="images/favicon/favicon.ico",
        source_method="realfavicongenerator.net",
    ),
    asset(
        name="Favicon — favicon.svg",
        category="site-identity", subcategory="favicon",
        status="shipped", owner="kiran",
        purpose="Modern browser pinned tab support (vector)",
        file_format="SVG",
        output_path="images/favicon/favicon.svg",
    ),
    asset(
        name="Favicon — favicon-96x96.png",
        category="site-identity", subcategory="favicon",
        status="shipped", owner="kiran",
        purpose="96×96 PNG favicon",
        dimensions="96×96",
        file_format="PNG",
        output_path="images/favicon/favicon-96x96.png",
    ),
    asset(
        name="Apple touch icon",
        category="site-identity", subcategory="favicon",
        status="shipped", owner="kiran",
        purpose="iOS home screen icon when site is added to home screen",
        dimensions="180×180",
        file_format="PNG",
        output_path="images/favicon/apple-touch-icon.png",
    ),
    asset(
        name="Web app manifest 192",
        category="site-identity", subcategory="favicon",
        status="shipped", owner="kiran",
        purpose="PWA install icon (192×192)",
        dimensions="192×192",
        file_format="PNG",
        output_path="images/favicon/web-app-manifest-192x192.png",
    ),
    asset(
        name="Web app manifest 512",
        category="site-identity", subcategory="favicon",
        status="shipped", owner="kiran",
        purpose="PWA install icon (512×512)",
        dimensions="512×512",
        file_format="PNG",
        output_path="images/favicon/web-app-manifest-512x512.png",
    ),
    asset(
        name="site.webmanifest",
        category="site-identity", subcategory="favicon",
        status="shipped", owner="kiran",
        purpose="JSON PWA manifest — name, icons, theme color, install behavior",
        file_format="JSON",
        output_path="images/favicon/site.webmanifest",
    ),
    asset(
        name="Logo / wordmark",
        category="site-identity", subcategory="logo",
        status="shipped", owner="kiran",
        purpose="Primary logo on site nav. Future state: SVG variant + monochrome variants needed.",
        file_format="PNG",
        output_path="images/logo.png",
        notes="Could use SVG conversion + monochrome variants for stationery/print.",
    ),

    # ─── 03. CONTENT SURFACES ───────────────────────────────────
    asset(
        name="Bento card art (full system)",
        category="content-surfaces", subcategory="bento",
        status="shipped", owner="kiran",
        purpose="Per-persona-per-slot character illustrations across 9 cards × 7 personas. 23 unique images covering all 63 combos.",
        where_deployed="Homepage bento grid",
        quantity=23,
        file_format="PNG",
        output_path="images/ (flat — see BENTO-CARD-GAMEPLAN.md)",
        naming_pattern="[character]-[slot]-[ratio].png",
        style_direction="Pixar / Monsters Inc quality. Warm golden-hour. Per-character thematic environments. Compose for glassmorphism overlay dead-zone.",
        source_method="Midjourney v7 (sref pixar-style + per-character oref)",
    ),
    asset(
        name="Persona portraits (set of 6)",
        category="content-surfaces", subcategory="personas",
        status="shipped", owner="kiran",
        purpose="Full-body character portraits for persona picker selection screen.",
        where_deployed="Persona picker (homepage first load)",
        aspect_ratio="3:4 portrait",
        file_format="PNG + WebP",
        quantity=6,
        output_path="images/{persona}-{name}.png",
        notes="Files: evaluator-merritt, seeker-phil, practitioner-drew, learner-paige, technologist-ray, innercircle-keshav",
    ),
    asset(
        name="OG share cards (9 per content type)",
        category="content-surfaces", subcategory="og-cards",
        status="shipped", owner="kiran",
        purpose="Per-content-type social link previews. 1200×630 (1.91:1).",
        where_deployed="og:image meta tag on every site page",
        dimensions="1200×630",
        aspect_ratio="1.91:1",
        file_format="PNG",
        quantity=9,
        output_path="images/og/og-{type}.png",
        style_direction="Bento hero image as background + thin cream bottom band (120px) with eyebrow + title + byline. Generated programmatically.",
        source_method="Programmatic (PIL via scripts/generate-og-cards.py)",
    ),
    asset(
        name="404 / error page monster",
        category="content-surfaces", subcategory="error-imagery",
        status="shipped", owner="kiran",
        purpose="Monster illustration shared across 404, 500, 503, maintenance pages.",
        where_deployed="404.html, 500.html, 503.html, maintenance.html (via error-styles.css)",
        aspect_ratio="~16:9",
        file_format="PNG",
        output_path="images/404image.png",
        style_direction="Construction-monster Pixar character, hard hat + tool belt + blueprint, warm golden lighting.",
        source_method="Midjourney",
    ),

    # ─── FENIX MASCOT (the phoenix character system) ────────────
    asset(
        name="Fenix mascot — avatar",
        category="site-identity", subcategory="fenix-mascot",
        status="shipped", owner="kiran",
        purpose="Calm canonical Fenix portrait, head and chest. Used as chat widget avatar, favicon-mode, small thumbnail across CC and product surfaces.",
        where_deployed="index.html line 374 — 'Meet Fenix' intro logo (replaced images/logo.png). Future: chat widget avatar, alternate favicon (Fenix mode), CC dashboard Fenix tile.",
        aspect_ratio="1:1",
        file_format="PNG",
        output_path="images/fenix/1fenixavatar1.png",
        style_direction="Pixar character animation cartoon mascot phoenix with raptor anatomy. Oversized expressive head, big warm friendly eyes, hooked eagle beak, prominent character brow. Subtle flame plumes on crest, gentle embers. Yellow chest, amber shoulders, crimson wingtips. Cream background.",
        source_method="Midjourney v7",
        preview_image_url="/images/fenix/1fenixavatar1.png",
        notes="Calm canonical of the two-canonical Fenix system. Pair with maintenance regeneration (full-fire variant). Used as --sref anchor for downstream variants.",
    ),
    asset(
        name="Fenix mascot — OG hero",
        category="site-identity", subcategory="fenix-mascot",
        status="shipped", owner="kiran",
        purpose="Three-quarter body Fenix for social link previews on Fenix-related pages.",
        where_deployed="Available as og:image at images/og/og-fenix.png — wired on demand for any Fenix-related page",
        dimensions="1200×630",
        aspect_ratio="1.91:1",
        file_format="PNG",
        output_path="images/fenix/2fenixhero1.png",
        style_direction="Same Fenix character. Three-quarter body, relaxed alert pose. Right third of frame reserved for headline typography overlay.",
        source_method="Midjourney v7 (sref to canonical avatar)",
        preview_image_url="/images/fenix/2fenixhero1.png",
        notes="Source file lives in images/fenix/. Copied to images/og/og-fenix.png to match the per-content-type OG card naming pattern — that path is what gets referenced in og:image meta tags.",
    ),
    asset(
        name="Fenix mascot — bento card hero",
        category="site-identity", subcategory="fenix-mascot",
        status="shipped", owner="kiran",
        purpose="Workshop-studio scene of Fenix at work. Wired as the hero image on the site's password gate (under-construction overlay) — the first thing every visitor sees.",
        where_deployed="gate.js — site access gate (password overlay shown before any page until visitor enters workshop2026). Future: also slated for a homepage Fenix bento slot when the bento gets redesigned.",
        aspect_ratio="2:1",
        file_format="PNG",
        output_path="images/fenix/3fenixbento.png",
        style_direction="Same Fenix character in a softly-lit warm studio environment, perched beside a glowing screen suggesting AI-assistant-at-work. Bottom-left dead zone for overlay.",
        source_method="Midjourney v7 (sref to canonical avatar)",
        preview_image_url="/images/fenix/3fenixbento.png",
        notes="Originally seeded for a homepage bento Fenix slot (currently no slot exists). Repurposed as the gate hero — the workshop scene matches the 'site being built' message exactly.",
    ),
    asset(
        name="Fenix mascot — error sign-holder",
        category="site-identity", subcategory="fenix-mascot",
        status="shipped", owner="kiran",
        purpose="Apologetic Fenix holding a blank sign — the friendly error illustration for 404 / 500 / 503. Replaced the construction monster (images/404image.png).",
        where_deployed="error-styles.css default .error-hero — applied across 404.html, 500.html, 503.html",
        aspect_ratio="16:9",
        file_format="PNG",
        output_path="images/fenix/4fenixerror.png",
        style_direction="Same Fenix character standing sheepishly, holding blank wooden / paper sign in front of chest with one wing. Body language reads 'oops, sorry about that' — head tilted, free wing in shrug or back-of-head scratch.",
        source_method="Midjourney v7 (sref to canonical avatar)",
        preview_image_url="/images/fenix/4fenixerror.png",
        notes="Sign is intentionally blank in source asset — text gets layered in via CSS or per-page render so each error code can show different copy.",
    ),
    asset(
        name="Fenix mascot — maintenance regeneration",
        category="site-identity", subcategory="fenix-mascot",
        status="shipped", owner="kiran",
        purpose="Fenix mid-rebirth, body fully engulfed in active flames. Used on the maintenance / lockdown screen — the phoenix metaphor IS the maintenance metaphor. Copy reads 'Fenix is regenerating. Back shortly.'",
        where_deployed="maintenance.html — applied via body.fenix-regenerating override in error-styles.css",
        aspect_ratio="16:9",
        file_format="PNG",
        output_path="images/fenix/5fenixmaintainance.png",
        style_direction="Same character but FULL-fire variant — entire body engulfed in active warm flames, rising calmly from soft glowing embers, head held up serenely, ONE wing softly raised. Inviting fire, not threatening — golden ember light, drifting sparks, no smoke.",
        source_method="Midjourney v7 (sref to flame canonical, sw 300)",
        preview_image_url="/images/fenix/5fenixmaintainance.png",
        notes="Flame canonical of the two-canonical Fenix system. Filename has typo (maintainance vs maintenance) — keep as-is for now to avoid breaking links.",
    ),
    asset(
        name="Fenix mascot — manifesto opening frame",
        category="site-identity", subcategory="fenix-mascot",
        status="shipped", owner="kiran",
        purpose="Opening frame source for the manifesto video. Fenix walking into frame from the right, looking at camera, ready to speak.",
        where_deployed="index.html manifesto section (C10) — wired as background-image poster on .manifesto-placeholder in styles.css. Also slated as source frame for videos/manifesto.mp4 once that lands.",
        aspect_ratio="16:9",
        file_format="PNG",
        output_path="images/fenix/6fenixmanifesto.png",
        style_direction="Same Fenix character entering frame from right, walking calmly forward, looking directly at camera, body language of a character about to speak. Soft warm depth-of-field studio behind. Negative space on right for first text title to fade in.",
        source_method="Midjourney v7 (sref to canonical avatar)",
        preview_image_url="/images/fenix/6fenixmanifesto.png",
        notes="Source frame for video. Animation/motion treatment is a separate workstream — this is the still that anchors it.",
    ),

    # ─── 04. MARKETING (most still uncommitted) ─────────────────
    asset(
        name="LinkedIn banner",
        category="marketing", subcategory="banners",
        status="uncommitted", owner="kiran",
        purpose="Header banner for LinkedIn profile. Brand consistency from site to social.",
        where_deployed="linkedin.com/in/[handle] header",
        aspect_ratio="4:1",
        dimensions="1584×396",
        file_format="PNG",
        output_path="images/marketing-kit/banners/banner-01-linkedin.png",
        style_direction="Mid-century editorial, Saul Bass / Paul Rand inspired. Cream background dominant + amber/teal/olive/rust accents. Leave clean dead-zone for typography overlay.",
        source_method="Midjourney + Canva (typography)",
    ),
    asset(
        name="Twitter/X banner",
        category="marketing", subcategory="banners",
        status="uncommitted", owner="kiran",
        purpose="Header banner for Twitter/X profile",
        where_deployed="x.com/[handle] header",
        aspect_ratio="3:1",
        dimensions="1500×500",
        file_format="PNG",
        output_path="images/marketing-kit/banners/banner-02-twitter.png",
        source_method="Midjourney + Canva",
    ),
    asset(
        name="GitHub profile banner",
        category="marketing", subcategory="banners",
        status="uncommitted", owner="kiran",
        purpose="Header banner for GitHub profile README",
        where_deployed="github.com/[handle] profile README",
        aspect_ratio="2:1",
        dimensions="1280×640",
        file_format="PNG",
        output_path="images/marketing-kit/banners/banner-03-github.png",
        source_method="Midjourney + Canva",
    ),
    asset(
        name='"What is this site?" handout',
        category="marketing", subcategory="handout",
        status="uncommitted", owner="kiran",
        purpose="Single shareable image pasted in DMs and warm intros. Explains the site at a glance.",
        aspect_ratio="1:1",
        file_format="PNG",
        output_path="images/marketing-kit/handout/handout-01-what-is-this.png",
        style_direction="Mid-century editorial. Workshop/studio abstract composition. Bottom-third dead zone for typography.",
        source_method="Midjourney + Canva",
    ),
    asset(
        name="Mood board imagery (8)",
        category="marketing", subcategory="mood-board",
        status="uncommitted", owner="kiran",
        purpose="Visual references that anchor the brand identity. Lives in brand board (HTML).",
        aspect_ratio="1:1",
        file_format="PNG",
        quantity=8,
        output_path="images/marketing-kit/mood-board/mood-{N}-{descriptor}.png",
        style_direction="Mid-century editorial. Each image a single bold composition idea — no clutter, character, or text.",
        source_method="Midjourney",
    ),
    asset(
        name="Social media campaign concepts (8-10)",
        category="marketing", subcategory="social-concepts",
        status="uncommitted", owner="kiran",
        purpose="Hypothetical IG/Twitter/LinkedIn launch campaign. Lives in marketing kit case study.",
        aspect_ratio="1:1",
        file_format="PNG",
        quantity=10,
        output_path="images/marketing-kit/social-concepts/social-{N}-{concept}.png",
        style_direction="Mid-century editorial. Designer adds headline typography in Canva post-MJ.",
        source_method="Midjourney + Canva",
    ),

    # ─── 05. VIDEO ──────────────────────────────────────────────
    asset(
        name="Hero cinemagraph",
        category="video", subcategory="hero",
        status="parked", owner="kiran",
        purpose="Animated version of homepage hero. Replaces static <picture> with <video>. Subtle motion only — steam, dog breathing, light shift.",
        where_deployed="index.html lines 147-152",
        dimensions="1920×1080 or 2560×1440",
        file_format="MP4 H.264 + WebM",
        file_size_target="<3MB",
        output_path="videos/hero-cinemagraph.mp4 + .webm",
        source_method="Runway Gen-4 (image-to-video)",
        notes="Full spec in docs/Website/Homepage/CONTINUATION-BENTO-HERO-COMPLETION.md",
    ),
    asset(
        name='Manifesto / "Why this site exists" video',
        category="video", subcategory="manifesto",
        status="parked", owner="kiran",
        purpose="45-60s click-to-play video below Fenix intro. Section C10 shell already shipped.",
        where_deployed="index.html line ~340 (HTML comment marks insertion point)",
        file_format="MP4",
        output_path="videos/manifesto.mp4 + images/manifesto-poster.webp",
        source_method="HeyGen / Runway / self-filmed (decision pending)",
        notes="Script locked in docs/PersonaPicker/PERSONA-PICKER.md §9",
    ),

    # ─── 01. BRAND FUNDAMENTALS ─────────────────────────────────
    asset(
        name="Color palette spec",
        category="brand-fundamentals", subcategory="palette",
        status="shipped", owner="kiran",
        purpose="Canonical color tokens — primary cream, deep ink, accent ambers/teals, semantic colors.",
        where_deployed="styles.css :root variables, VISUAL-STANDARDS.md",
        file_format="CSS + reference doc",
        output_path="docs/Foundation/VISUAL-STANDARDS.md",
        notes="Living spec. Tokens use oklch color space.",
    ),
    asset(
        name="Typography system",
        category="brand-fundamentals", subcategory="typography",
        status="shipped", owner="kiran",
        purpose="Font families, weights, scale ramp, line-height system.",
        where_deployed="styles.css + VISUAL-STANDARDS.md",
        file_format="CSS + reference doc",
        output_path="docs/Foundation/VISUAL-STANDARDS.md",
    ),
    asset(
        name="Character / monster system",
        category="brand-fundamentals", subcategory="characters",
        status="shipped", owner="kiran",
        purpose="9 monsters mapped to content types. Pixar/Monsters-Inc style. Character bibles per role.",
        where_deployed="Bento art, OG cards, 404 page",
        source_method="Midjourney v7 character refs",
        notes="Established Phase A. Source refs locked.",
    ),
    asset(
        name="Aesthetic / visual language doc",
        category="brand-fundamentals", subcategory="aesthetics",
        status="uncommitted", owner="tbd",
        purpose="Plain-English description of the look — what the brand feels like, what it's not.",
        file_format="Markdown",
        output_path="docs/Foundation/BRAND-AESTHETIC.md",
        notes="Useful for designer onboarding + AI prompt anchoring.",
        estimated_effort="small",
    ),

    # ─── 06. STATIONERY ─────────────────────────────────────────
    asset(
        name="Business card — front",
        category="stationery", subcategory="business-card",
        status="uncommitted", owner="designer",
        purpose="Networking / conference handout. Name + title + URL + QR code.",
        dimensions='3.5"×2" (1050×600 @300dpi)',
        aspect_ratio="7:4",
        file_format="PDF print-ready + PNG mockup",
        file_size_target="<2MB print PDF",
        quantity=1,
        output_path="brand-kit/stationery/business-card-front.pdf",
        style_direction="Cream stock + deep-ink type. Mid-century editorial. QR code in subtle accent color. Spot UV optional.",
        source_method="Designer (Figma → print ready PDF)",
        notes="Print spec: full bleed 0.125\", safe zone 0.125\".",
    ),
    asset(
        name="Business card — back",
        category="stationery", subcategory="business-card",
        status="uncommitted", owner="designer",
        purpose="Reverse side — single design element (monster mark / wordmark / quote).",
        dimensions='3.5"×2" (1050×600 @300dpi)',
        aspect_ratio="7:4",
        file_format="PDF print-ready",
        output_path="brand-kit/stationery/business-card-back.pdf",
        source_method="Designer",
    ),
    asset(
        name="Letterhead",
        category="stationery", subcategory="letterhead",
        status="uncommitted", owner="designer",
        purpose="A4/Letter size letterhead for formal correspondence.",
        dimensions='8.5"×11" (Letter)',
        file_format="PDF + .docx editable",
        output_path="brand-kit/stationery/letterhead.docx",
        style_direction="Subtle header band, minimal footer. Prints clean B&W as fallback.",
        source_method="Designer",
    ),
    asset(
        name="Envelope (#10)",
        category="stationery", subcategory="envelope",
        status="uncommitted", owner="designer",
        purpose="Standard #10 business envelope with return address.",
        dimensions='9.5"×4.125"',
        file_format="PDF print-ready",
        output_path="brand-kit/stationery/envelope-10.pdf",
        source_method="Designer",
    ),
    asset(
        name="Notecard / thank-you card",
        category="stationery", subcategory="notecard",
        status="uncommitted", owner="designer",
        purpose="Folded notecard for thank-yous after meetings, intros, gifts.",
        dimensions='5"×7" folded',
        file_format="PDF print-ready",
        output_path="brand-kit/stationery/notecard.pdf",
        source_method="Designer",
    ),
    asset(
        name="Business card holder design",
        category="stationery", subcategory="accessories",
        status="uncommitted", owner="tbd",
        purpose="Optional — branded business card holder for events.",
        file_format="Vendor template",
        notes="Low priority. Skip unless designer wants to spec it for completeness.",
        estimated_effort="small",
    ),

    # ─── 07. DOCUMENTS ──────────────────────────────────────────
    asset(
        name="Pitch deck — full template",
        category="documents", subcategory="deck",
        status="uncommitted", owner="designer",
        purpose="Slide template for pitches, talks, investor updates. Title / section / content / data slide variants.",
        aspect_ratio="16:9",
        file_format=".pptx + .key + Google Slides",
        quantity=1,
        output_path="brand-kit/documents/deck-template.pptx",
        style_direction="Cream slides, deep-ink type, character art on section dividers, mid-century chart styling.",
        source_method="Designer",
        notes="Should include: title, section divider, content (1-3 col), quote, data, image-bleed, contact slide.",
    ),
    asset(
        name="Resume template — full kit",
        category="documents", subcategory="resume",
        status="shipped", owner="kiran",
        purpose="9 resume templates (3 personas × 3 lengths) used by customize-resume skill.",
        file_format=".docx",
        output_path="customize-resume/editable_templates/",
        quantity=9,
        notes="Lives in skill folder, not brand-kit/. Templates already shipped.",
    ),
    asset(
        name="One-pager — about Kiran",
        category="documents", subcategory="one-pager",
        status="uncommitted", owner="designer",
        purpose="Single-page intro doc — what Kiran does, who it's for, how to engage.",
        dimensions='8.5"×11"',
        file_format="PDF",
        output_path="brand-kit/documents/one-pager.pdf",
        style_direction="Editorial layout, character art on margin. Like a magazine spread, not a brochure.",
        source_method="Designer",
    ),
    asset(
        name="Case study template",
        category="documents", subcategory="case-study",
        status="uncommitted", owner="designer",
        purpose="Reusable template for writing up projects (Track Record stories, MadLab experiments).",
        file_format=".docx + Google Docs template",
        output_path="brand-kit/documents/case-study-template.docx",
        notes="Should map cleanly to teardowns site format.",
    ),
    asset(
        name="Press release template",
        category="documents", subcategory="press-release",
        status="uncommitted", owner="designer",
        purpose="Standard press release format with branded header.",
        file_format=".docx",
        output_path="brand-kit/documents/press-release-template.docx",
        estimated_effort="small",
    ),
    asset(
        name="Invoice template",
        category="documents", subcategory="invoice",
        status="uncommitted", owner="designer",
        purpose="Branded invoice for any future consulting / advisory work.",
        file_format=".docx + .xlsx",
        output_path="brand-kit/documents/invoice-template.xlsx",
        estimated_effort="small",
    ),
    asset(
        name="Proposal template",
        category="documents", subcategory="proposal",
        status="uncommitted", owner="designer",
        purpose="Multi-page proposal/SOW template with cover, scope, timeline, pricing sections.",
        file_format=".docx + Google Docs template",
        output_path="brand-kit/documents/proposal-template.docx",
        estimated_effort="medium",
    ),
    asset(
        name="Contract / agreement template",
        category="documents", subcategory="contract",
        status="uncommitted", owner="tbd",
        purpose="Branded contract template (cover/header treatment only — legal text from lawyer).",
        file_format=".docx",
        output_path="brand-kit/documents/contract-template.docx",
        notes="Branding only. Body content is lawyer-supplied.",
    ),
    asset(
        name="Memo / brief template",
        category="documents", subcategory="memo",
        status="uncommitted", owner="designer",
        purpose="Short-form memo template for sharing thinking in a structured way.",
        file_format=".docx + Google Docs",
        output_path="brand-kit/documents/memo-template.docx",
        estimated_effort="small",
    ),

    # ─── 08. EMAIL ──────────────────────────────────────────────
    asset(
        name="Email signature",
        category="email", subcategory="signature",
        status="uncommitted", owner="designer",
        purpose="Branded email signature block — name, role, links, optional headshot.",
        file_format="HTML + plaintext fallback",
        output_path="brand-kit/email/signature.html",
        style_direction="Type-only or with small monster mark. Loads cleanly on dark/light email clients.",
        source_method="HTML/CSS",
        notes="Test in Gmail, Outlook, Apple Mail — image vs. type-only versions.",
    ),
    asset(
        name="Newsletter template",
        category="email", subcategory="newsletter",
        status="uncommitted", owner="designer",
        purpose="If/when Kiran sends a newsletter — branded HTML email template.",
        dimensions="600px wide",
        file_format="HTML email template",
        output_path="brand-kit/email/newsletter-template.html",
        notes="Match site editorial voice. Substack/Beehiiv/ConvertKit compatible.",
        estimated_effort="medium",
    ),
    asset(
        name="Cold outreach email template",
        category="email", subcategory="outreach",
        status="uncommitted", owner="kiran",
        purpose="Branded HTML email for warm intros / cold outreach (with signature + intro paragraph).",
        file_format="HTML",
        output_path="brand-kit/email/outreach-template.html",
        estimated_effort="small",
    ),

    # ─── 09. SPEAKING ───────────────────────────────────────────
    asset(
        name="Speaker bio (short + long)",
        category="speaking", subcategory="bio",
        status="uncommitted", owner="kiran",
        purpose="Three lengths of speaker bio — 1 sentence / 1 paragraph / full page — for conference programs.",
        file_format="Markdown",
        output_path="brand-kit/speaking/speaker-bio.md",
        notes="Single source of truth. All three lengths in one file with separators.",
        estimated_effort="small",
    ),
    asset(
        name="Title slide template",
        category="speaking", subcategory="title-slide",
        status="uncommitted", owner="designer",
        purpose="First slide for any talk. Talk title + name + venue + date.",
        aspect_ratio="16:9",
        file_format=".pptx + .key",
        output_path="brand-kit/speaking/title-slide.pptx",
        style_direction="Bold typography, minimal art. Should work as social-share image too.",
        source_method="Designer",
    ),
    asset(
        name="Zoom / video call backgrounds",
        category="speaking", subcategory="zoom-bg",
        status="uncommitted", owner="designer",
        purpose="Branded virtual backgrounds for Zoom/Meet/Teams — 2-3 variants.",
        dimensions="1920×1080",
        aspect_ratio="16:9",
        file_format="PNG",
        quantity=3,
        output_path="brand-kit/speaking/zoom-bg-{variant}.png",
        style_direction="Subtle character art behind, doesn't compete with face. Optional bookshelf / studio variants.",
        source_method="Midjourney + Canva",
    ),
    asset(
        name="Podcast cover art",
        category="speaking", subcategory="podcast",
        status="uncommitted", owner="designer",
        purpose="Square cover art if Kiran ever launches a podcast.",
        dimensions="3000×3000",
        aspect_ratio="1:1",
        file_format="PNG + JPG",
        output_path="brand-kit/speaking/podcast-cover.png",
        notes="Speculative. Park if podcast not on roadmap.",
        estimated_effort="medium",
    ),
    asset(
        name="Speaker headshot variants",
        category="speaking", subcategory="headshot",
        status="uncommitted", owner="kiran",
        purpose="Multiple-angle headshot set for speaker pages, press, social.",
        file_format="PNG + JPG, multiple resolutions",
        quantity=4,
        output_path="brand-kit/speaking/headshot-{variant}.jpg",
        notes="Photographer needed. Coordinate with future-state press kit.",
        estimated_effort="large",
    ),

    # ─── 10. PLATFORM ───────────────────────────────────────────
    asset(
        name="LinkedIn avatar",
        category="platform", subcategory="avatar",
        status="uncommitted", owner="kiran",
        purpose="Profile photo for LinkedIn. Same source as site headshot.",
        dimensions="800×800",
        aspect_ratio="1:1",
        file_format="JPG",
        output_path="brand-kit/platform/avatar-linkedin.jpg",
        estimated_effort="small",
    ),
    asset(
        name="Twitter/X avatar",
        category="platform", subcategory="avatar",
        status="uncommitted", owner="kiran",
        purpose="Profile photo for X.",
        dimensions="400×400",
        aspect_ratio="1:1",
        file_format="JPG",
        output_path="brand-kit/platform/avatar-twitter.jpg",
        estimated_effort="small",
    ),
    asset(
        name="GitHub avatar",
        category="platform", subcategory="avatar",
        status="uncommitted", owner="kiran",
        purpose="Profile photo for GitHub.",
        dimensions="460×460",
        aspect_ratio="1:1",
        file_format="PNG",
        output_path="brand-kit/platform/avatar-github.png",
        estimated_effort="small",
    ),
    asset(
        name="GitHub social preview",
        category="platform", subcategory="github-social",
        status="uncommitted", owner="designer",
        purpose="Social card shown when a GitHub repo is linked anywhere (per-repo).",
        dimensions="1280×640",
        aspect_ratio="2:1",
        file_format="PNG",
        output_path="brand-kit/platform/github-social-{repo}.png",
        style_direction="Repo name + tagline + monster mark. Mid-century editorial.",
        source_method="Designer",
    ),
    asset(
        name="Slack workspace icon",
        category="platform", subcategory="workspace-icon",
        status="uncommitted", owner="designer",
        purpose="Square Slack workspace icon.",
        dimensions="512×512",
        aspect_ratio="1:1",
        file_format="PNG",
        output_path="brand-kit/platform/slack-icon.png",
        estimated_effort="small",
    ),
    asset(
        name="Notion / workspace icons",
        category="platform", subcategory="workspace-icon",
        status="uncommitted", owner="designer",
        purpose="Tiny icons for Notion workspace, browser bookmarks, etc.",
        dimensions="512×512",
        aspect_ratio="1:1",
        file_format="PNG",
        quantity=3,
        output_path="brand-kit/platform/workspace-icon-{tool}.png",
        estimated_effort="small",
    ),

    # ─── 11. PRINT ──────────────────────────────────────────────
    asset(
        name="Sticker sheet",
        category="print", subcategory="stickers",
        status="uncommitted", owner="designer",
        purpose="Vinyl stickers — monster characters, wordmark, key phrases. Conference giveaways.",
        file_format="PDF print-ready",
        quantity=6,
        output_path="brand-kit/print/sticker-sheet.pdf",
        style_direction="Die-cut. Bright but on-palette. Mix of character mark + wordmark + small phrases.",
        source_method="Designer",
    ),
    asset(
        name="Conference poster",
        category="print", subcategory="posters",
        status="uncommitted", owner="designer",
        purpose="Large-format poster for any speaking engagement / event sponsor presence.",
        dimensions='24"×36"',
        file_format="PDF print-ready",
        output_path="brand-kit/print/poster-event.pdf",
        notes="Mid-century editorial. Saul Bass / National Park poster aesthetic.",
        estimated_effort="medium",
    ),
    asset(
        name="T-shirt design",
        category="print", subcategory="merch",
        status="uncommitted", owner="designer",
        purpose="Branded t-shirt — front mark + optional back design. Conference / launch giveaway.",
        file_format="AI / EPS print-ready",
        output_path="brand-kit/print/tshirt-design.ai",
        notes="DTG or screen-print compatible.",
        estimated_effort="medium",
    ),
    asset(
        name="Tote bag design",
        category="print", subcategory="merch",
        status="uncommitted", owner="designer",
        purpose="Branded tote bag — wordmark or monster character.",
        file_format="AI / EPS print-ready",
        output_path="brand-kit/print/tote-design.ai",
        estimated_effort="small",
    ),
    asset(
        name="Notebook / journal cover",
        category="print", subcategory="merch",
        status="uncommitted", owner="designer",
        purpose="Branded notebook cover — debossed/foil mark.",
        file_format="AI / EPS",
        output_path="brand-kit/print/notebook-cover.ai",
        notes="Vendor-dependent (Moleskine custom, Field Notes, etc.).",
    ),
    asset(
        name="Conference name badge",
        category="print", subcategory="badge",
        status="uncommitted", owner="designer",
        purpose="Custom name badge for events Kiran hosts/co-hosts.",
        dimensions='4"×3"',
        file_format="PDF print-ready",
        output_path="brand-kit/print/name-badge.pdf",
        estimated_effort="small",
    ),

    # ─── 12. BRAND DOCS ─────────────────────────────────────────
    asset(
        name="Brand guidelines document",
        category="brand-docs", subcategory="guidelines",
        status="uncommitted", owner="designer",
        purpose="Master brand guidelines — palette, type, voice, logo usage, character system, examples.",
        file_format="PDF + .indd source",
        output_path="brand-kit/brand-docs/brand-guidelines.pdf",
        style_direction="Editorial design publication. Like a real magazine, not a corporate slide deck.",
        source_method="Designer",
        estimated_effort="large",
        notes="The capstone artifact. Compiles every other brand-doc asset.",
    ),
    asset(
        name="Voice & tone guide",
        category="brand-docs", subcategory="voice",
        status="shipped", owner="kiran",
        purpose="Voice rules, banned phrases, authenticity standards. Already written.",
        where_deployed="docs/Foundation/CONTENT-STANDARDS.md, AUTHENTICITY-STANDARDS.md, CONTENT-GOVERNANCE.md",
        file_format="Markdown",
        output_path="docs/Foundation/CONTENT-STANDARDS.md",
        notes="Three docs together comprise the full voice spec.",
    ),
    asset(
        name="Logo lockup variants",
        category="brand-docs", subcategory="logo-lockups",
        status="uncommitted", owner="designer",
        purpose="Horizontal / stacked / mark-only / monochrome / inverted variants of the logo.",
        file_format="SVG + PNG (multiple sizes)",
        quantity=6,
        output_path="brand-kit/brand-docs/logo-lockups/",
        source_method="Designer",
        notes="Replaces existing single PNG logo with proper system.",
    ),
    asset(
        name="Color palette spec sheet",
        category="brand-docs", subcategory="palette-spec",
        status="uncommitted", owner="designer",
        purpose="Print-ready palette spec — hex / RGB / CMYK / Pantone / oklch.",
        file_format="PDF",
        output_path="brand-kit/brand-docs/palette-spec.pdf",
        notes="Generates from VISUAL-STANDARDS.md tokens.",
        estimated_effort="small",
    ),
    asset(
        name="Type spec sheet",
        category="brand-docs", subcategory="type-spec",
        status="uncommitted", owner="designer",
        purpose="Type system spec — fonts, weights, scale, line-height, letter-spacing for digital + print.",
        file_format="PDF",
        output_path="brand-kit/brand-docs/type-spec.pdf",
    ),
    asset(
        name="Icon set",
        category="brand-docs", subcategory="icon-set",
        status="uncommitted", owner="designer",
        purpose="Custom icon system — replaces generic Lucide / Heroicons throughout site + decks.",
        file_format="SVG",
        quantity=24,
        output_path="brand-kit/brand-docs/icon-set/",
        style_direction="Mid-century editorial line work. Slightly hand-drawn feel.",
        estimated_effort="large",
    ),
    asset(
        name="Pattern library",
        category="brand-docs", subcategory="patterns",
        status="uncommitted", owner="designer",
        purpose="Reusable background patterns / textures for marketing collateral.",
        file_format="SVG + PNG tile-able",
        quantity=4,
        output_path="brand-kit/brand-docs/patterns/",
        estimated_effort="medium",
    ),
    asset(
        name="Photo treatment guide",
        category="brand-docs", subcategory="photo-treatment",
        status="uncommitted", owner="designer",
        purpose="LUT / color grade preset for any photography shot for the brand.",
        file_format=".cube LUT + Lightroom preset",
        output_path="brand-kit/brand-docs/photo-treatment.cube",
        estimated_effort="medium",
    ),
    asset(
        name="Watermark / signature mark",
        category="brand-docs", subcategory="watermark",
        status="uncommitted", owner="designer",
        purpose="Subtle mark for protecting / signing original artwork posted online.",
        file_format="SVG + PNG",
        output_path="brand-kit/brand-docs/watermark.svg",
        estimated_effort="small",
    ),

    # ─── 13. FUTURE STATE (low-priority / aspirational) ─────────
    asset(
        name="Professional headshots",
        category="future-state", subcategory="headshots",
        status="uncommitted", owner="kiran",
        purpose="Studio-quality headshots — multiple expressions / wardrobe / backgrounds.",
        file_format="JPG + retouched RAW",
        quantity=10,
        output_path="brand-kit/future/headshots/",
        notes="Photographer engagement needed. Coordinate with speaker headshots above.",
        estimated_effort="large",
    ),
    asset(
        name="Press kit",
        category="future-state", subcategory="press-kit",
        status="uncommitted", owner="kiran",
        purpose="Bundle of speaker bios, headshots, logos, fact sheet — for press inquiries.",
        file_format="ZIP bundle + landing page",
        output_path="brand-kit/future/press-kit.zip",
        notes="Aggregates assets from speaking + platform + brand-docs categories.",
        estimated_effort="medium",
    ),
]


def main():
    print(f"Seeding {len(ITEMS)} initial visual assets to {DATA_PATH}")
    DATA_PATH.write_text(json.dumps(ITEMS, indent=2, default=str))
    print(f"  ✓ wrote {len(ITEMS)} entries")
    print(f"  Status breakdown:")
    by_status = {}
    for item in ITEMS:
        by_status[item["status"]] = by_status.get(item["status"], 0) + 1
    for status, count in by_status.items():
        print(f"    {status}: {count}")
    print()
    print("  Next: run scripts/detect_visual_assets.py to auto-flip any uncommitted items whose files already exist on disk.")


if __name__ == "__main__":
    main()
