[sdl]
fullscreen=false

[render]
aspect=true
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=fixed 12000

[mixer]
nosound=false
rate=22050

[speaker]
pcspeaker=true
pcrate=22050

[autoexec]
@echo off
mount c .
c:
gwbasic RIVER.BAS
